language: minimal
before_script:
  - git clone https://github.com/bats-core/bats-core.git ~/bats-core
  - pushd ~/bats-core
  - ./install.sh $HOME
  - popd
  - sudo apt-get update
  - sudo apt-get install -y shellcheck
script:
  - shellcheck --shell=bash --exclude=SC2086,SC1090 ./{,**/}*.sh
  - bats --pretty test
